spring:
  application:
    name: TaskManager-task-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:file:./taskDb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8082
  servlet:
    context-path: /v1/api/task

springdoc:
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

variables:
  jwt-secret: "GSuovz7BIEJLvLCKwfhghwx8tHfK3ee4L2K9/VPHQhI="
  internal-secret: "w6YT3S43OL80iP67Fu2WjC3fXD1NPQYe"
  auth-uri: "http://localhost:8081/api/"




